services:
  hello-nas:
    path: hello-nas
    enabled: true

  plant-monitor:
    path: plant-monitor
    enabled: true

  plant-monitor-temporal:
    path: plant-monitor-temporal
    enabled: false

  portainer:
    path: portainer
    enabled: true

  dashy:
    path: dashy
    enabled: true

  homelab-functions:
    path: homelab-functions
    enabled: true

  hass-janitor:
    path: hass-janitor
    enabled: true

  temporal:
    path: temporal
    enabled: true

  homelab-log-watcher:
    path: homelab-log-watcher
    enabled: true
