host:
  name: macmini
  deploy_base_dir: ${HOME}/homelab-config-runtime
  bind_addr: 192.168.1.43

services:
  hello-nas:
    path: services/hello-nas
    enabled: true

  plant-monitor:
    path: services/plant-monitor
    enabled: false

  dashy:
    path: services/dashy
    enabled: false

  homelab-functions:
    path: services/homelab-functions
    enabled: false

  hass-janitor:
    path: services/hass-janitor
    enabled: false

  homelab-log-watcher:
    path: services/homelab-log-watcher
    enabled: false

  homelab-sre-agent:
    path: services/homelab-sre-agent
    enabled: false

  bedtime:
    path: services/bedtime
    enabled: false
