services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest@sha256:fc96436bf80000bed8989d6606fc1ac0929bf4809bb4594168ad4b327e8f2c5f
    container_name: homarr
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: ${TZ:-America/New_York}
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
    ports:
      - "${HOMARR_HTTP_PORT:-7575}:7575"
    volumes:
      - ./data:/appdata
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "1"
        compress: "false"
