services:
  plant-monitor-temporal:
    image: ghcr.io/feocco/plant-monitor:temporal
    container_name: plant-monitor-temporal
    restart: unless-stopped
    command: plant temporal-run
    env_file:
      - .env
    volumes:
      - ./plants.yaml:/app/plants.yaml:ro
      - ./data:/app/data
