services:
  dashy:
    image: lissy93/dashy:latest@sha256:ddf8197613f51f6dfd6c5b6395def0ec6ae56e15897926d6f7d3bff9d5bc55f0
    container_name: dashy
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CONF_PATH=/app/user-data/conf.yml
    env_file:
      - .env
    ports:
      - "${HOST_BIND_ADDR:-127.0.0.1}:${DASHY_HTTP_PORT:-8080}:8080"
    volumes:
      - ./user-data:/app/user-data
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "1"
        compress: "false"
