services:
  caddy:
    image: ghcr.io/feocco/homelab-caddy:2.11.4-cloudflare
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_BIND_ADDR:-0.0.0.0}:${CADDY_HTTP_PORT:-80}:80"
      - "${HOST_BIND_ADDR:-0.0.0.0}:${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "1"
        compress: "false"

volumes:
  caddy_data:
  caddy_config:
