host:
  name: nasfeo
  deploy_base_dir: /volume1/docker/homelab-config
  bind_addr: 192.168.1.191

services:
  hello-nas:
    path: services/hello-nas
    enabled: true

  plant-monitor:
    path: services/plant-monitor
    enabled: true

  portainer:
    path: services/portainer
    enabled: true

  dashy:
    path: services/dashy
    enabled: true

  homarr:
    path: services/homarr
    enabled: false

  netalertx:
    path: services/netalertx
    enabled: false

  homelab-functions:
    path: services/homelab-functions
    enabled: true

  hass-janitor:
    path: services/hass-janitor
    enabled: true

  homelab-log-watcher:
    path: services/homelab-log-watcher
    enabled: true

  homelab-sre-agent:
    path: services/homelab-sre-agent
    enabled: true

  homelab-monitor:
    path: services/homelab-monitor
    enabled: false

  bedtime:
    path: services/bedtime
    enabled: true
