apiVersion: 1

contactPoints:
  - orgId: 1
    name: homelab-phone
    receivers:
      - uid: homelab-phone-webhook
        type: webhook
        settings:
          url: http://192.168.1.191:8091/v1/notify/joe
          httpMethod: POST
          authorization_scheme: Bearer
          authorization_credentials: $__env{HOMELAB_FUNCTIONS_TOKEN}
          title: '{{ template "homelab.phone.title" . }}'
          message: '{{ template "homelab.phone.message" . }}'
          maxAlerts: 5
        disableResolveMessage: true
