apiVersion: 1

templates:
  - orgId: 1
    name: homelab-phone-template
    template: |
      {{ define "homelab.phone.title" -}}
      Homelab: {{ .CommonLabels.alertname }}
      {{- end }}

      {{ define "homelab.phone.message" -}}
      {{- range .Alerts -}}
      {{ if .Labels.service }}{{ .Labels.service }}{{ else if .Labels.container_label_io_kubernetes_container_name }}{{ .Labels.container_label_io_kubernetes_container_name }}{{ else if .Labels.name }}{{ .Labels.name }}{{ else }}{{ .Labels.instance }}{{ end }}: {{ .Annotations.summary }}
      {{- if .Annotations.description }}
      {{ .Annotations.description }}
      {{- end }}
      {{- end -}}
      {{- end }}
