services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.19.0
    container_name: mealie
    restart: unless-stopped
    environment:
      ALLOW_SIGNUP: ${ALLOW_SIGNUP:-false}
      ALLOW_PASSWORD_LOGIN: ${ALLOW_PASSWORD_LOGIN:-true}
      API_DOCS: ${API_DOCS:-false}
      BASE_URL: ${BASE_URL:-https://mealie.home.feocco.com}
      DB_ENGINE: postgres
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      DEFAULT_GROUP: ${DEFAULT_GROUP:-Home}
      DEFAULT_HOUSEHOLD: ${DEFAULT_HOUSEHOLD:-Family}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_WORKERS: ${OPENAI_WORKERS:-10}
      PGID: ${PGID:-1000}
      POSTGRES_DB: ${POSTGRES_DB:-mealie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_SERVER: mealie-postgres
      POSTGRES_USER: ${POSTGRES_USER:-mealie}
      PUID: ${PUID:-1000}
      SMTP_AUTH_STRATEGY: ${SMTP_AUTH_STRATEGY:-TLS}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL:-}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME:-Mealie}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-}
      TZ: ${TZ:-America/New_York}
    ports:
      - "${HOST_BIND_ADDR:-127.0.0.1}:${MEALIE_HTTP_PORT:-9925}:9000"
    volumes:
      - ./data/app:/app/data
    depends_on:
      mealie-postgres:
        condition: service_healthy
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "1"
        compress: "false"

  mealie-postgres:
    image: postgres:17
    container_name: mealie-postgres
    restart: unless-stopped
    environment:
      PGUSER: ${POSTGRES_USER:-mealie}
      POSTGRES_DB: ${POSTGRES_DB:-mealie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-mealie}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "1"
        compress: "false"

  mealie-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: mealie-cloudflared
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    command:
      - tunnel
      - --no-autoupdate
      - --loglevel
      - info
      - run
    depends_on:
      - mealie
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "1"
        compress: "false"
