server {
  listen 8080;
  server_name _;

  location = /health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location / {
    return 302 http://maclabs-mac-mini.taildf3445.ts.net:8080$request_uri;
  }
}
